export enum ExceptionCode {
  InvalidRequest = 'invalid_request',
  SomeFieldsAlreadyExists = 'some_fields_already_exists',
  InsufficientPermissions = 'insufficient_permissions',
  UnexpectedError = 'unexpected_error',
  ResourceNotFound = 'resource_not_found',
  RateLimit = 'rate_limit',
  Unauthorized = 'unauthorized',
  UnprocessableEntity = 'unprocessable_entity',
  ValidationFailed = 'validation_failed',
  IncorrectCredentials = 'incorrect_credentials',
  InactiveUser = 'inactive_user',
  InvalidToken = 'invalid_token',
  TokenInvalidOrActivityResolved = 'token_invalid_or_activity_resolved',
  ResolveTokenRequired = 'resolve_token_required',
  TokenExpired = 'token_expired',
  WrongMFACode = 'wrong_mfa_code',
  MFARequired = 'mfa_required',
  MFAAlreadyCompleted = 'mfa_already_completed',
  SuspiciousSession = 'suspicious_session',
  GoogleAuthFailed = 'google_auth_failed',
  GoogleAuthInvalidTokenPayload = 'google_auth_invalid_token_payload',
  GoogleAuthRequiresVerifiedEmail = 'google_auth_requires_verified_email',
  GoogleAuthMismatch = 'google_auth_mismatch',
}
